export const FETCH_LIST_PHOTOS = 'FETCH_LIST_PHOTOS';
export const REQUEST_LOADING_LIST_PHOTOS = 'REQUEST_LOADING_LIST_PHOTOS';
export const REQUEST_REJECTED_LIST_PHOTOS = 'REQUEST_REJECTED_LIST_PHOTOS';
